default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: localhost
  port: 5432
  pool: 50

development:
  <<: *default
  database: lawn_development

test:
  <<: *default
  database: lawn_test

production:
  <<: *default
  database: lawn_production
